server:
  port: 1111
eureka:
  instance:
    hostname: mongo-app
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017