server:
  port: 1111
eureka:
  instance:
    hostname: mongo-app
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
spring:
  data:
    mongodb:
      host: mongo-db
      port: 27017