server:
  port: 2222
eureka:
  instance:
    hostname: logger
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
spring:
  data:
    mongodb:
      host: mongo-db
      port: 27017
